from __future__ import annotations

from typing import Protocol

class InstrumentTransport(Protocol):
    resource: str
    def write(self, command: str) -> None: ...
    def query(self, command: str) -> str: ...
    def query_opc(self) -> str: ...
    def close(self) -> None: ...
