from __future__ import annotations

from typing import Protocol

class InstrumentTransport(Protocol):
    resource: str
    def write(self, command: str) -> None: ...
    def write_bytes(self, command: bytes) -> None: ...
    def query(self, command: str) -> str: ...
    def query_float_list(self, command: str) -> list[float]: ...
    def query_bin_block(self, command: str) -> bytes: ...
    def query_opc(self) -> str: ...
    def close(self) -> None: ...
