"""Dependency-neutral constants for the public scope extension contract."""

SCOPE_SCREENSHOT_BINARY_RESPONSE_MAX_BYTES = 262_144
SCOPE_SCREENSHOT_BINARY_OPERATION_MAX_BYTES = 262_144
SCOPE_SCREENSHOT_BINARY_QUERY_MAX_COUNT = 1
SCOPE_SCREENSHOT_BINARY_RESYNCHRONIZATION_MAX_BYTES = 0
SCOPE_TRACE_BINARY_RESPONSE_MAX_BYTES = 8_388_608
SCOPE_TRACE_BINARY_OPERATION_MAX_BYTES = 67_108_864
SCOPE_TRACE_BINARY_QUERY_MAX_COUNT = 256
SCOPE_TRACE_BINARY_RESYNCHRONIZATION_MAX_BYTES = 65_536
SCOPE_WAVEFORM_BINARY_RESPONSE_MAX_BYTES = 8_388_608
SCOPE_WAVEFORM_BINARY_OPERATION_MAX_BYTES = 67_108_864
SCOPE_WAVEFORM_BINARY_QUERY_MAX_COUNT = 256
SCOPE_WAVEFORM_BINARY_RESYNCHRONIZATION_MAX_BYTES = 65_536
SCOPE_PROFILE_OPERATION_TIMEOUT_MS = 5_000
SCOPE_SCREENSHOT_OPERATION_TIMEOUT_MS = 5_000
SCOPE_ACQUISITION_OPERATION_TIMEOUT_MS = 30_000
SCOPE_TRACE_OPERATION_TIMEOUT_MS = 60_000
SCOPE_WAVEFORM_OPERATION_TIMEOUT_MS = 60_000
SCOPE_SNAPSHOT_V2_OPERATION_TIMEOUT_MS = 60_000
SCOPE_TRACE_MAX_POINTS = 8_388_608

__all__ = [name for name in globals() if name.startswith("SCOPE_")]
