from __future__ import annotations

from .api import InstrumentPlugin

BUILTIN_PLUGINS: tuple[InstrumentPlugin, ...] = (
    InstrumentPlugin(
        driver_id="rohde-schwarz.rtm2032",
        kind="scope",
        display_name="Rohde & Schwarz RTM2032 Oscilloscope",
        manufacturer="Rohde & Schwarz",
        models=("RTM2032", "RTM2000"),
        capabilities=(
            "scope.idn",
            "scope.errors",
            "scope.autoscale",
            "scope.fetch_waveform",
            "scope.capture_waveform",
            "scope.capture_waveforms",
            "scope.screenshot",
            "scope.channel_coupling",
        ),
        summary="R&S RTM2000-series scope capture driver used by WaveBench scope services.",
        idn_patterns=("Rohde&Schwarz,RTM", "Rohde & Schwarz,RTM"),
        config_fields=("connection.resource", "scope.driver", "waveform.*"),
    ),
    InstrumentPlugin(
        driver_id="rigol.ds1104",
        kind="scope",
        display_name="RIGOL DS1104Z/DS1000Z Oscilloscope",
        manufacturer="RIGOL Technologies",
        models=("DS1104Z", "DS1104Z Plus", "DS1104Z-S Plus", "DS1000Z"),
        capabilities=(
            "scope.idn",
            "scope.errors",
            "scope.autoscale",
            "scope.fetch_waveform",
            "scope.capture_waveform",
            "scope.capture_waveforms",
            "scope.screenshot",
            "scope.channel_coupling",
        ),
        summary="RIGOL DS1000Z-series scope driver with BYTE waveform conversion and RAW chunking.",
        idn_patterns=("RIGOL TECHNOLOGIES,DS1104", "RIGOL TECHNOLOGIES,DS1"),
        config_fields=("connection.resource", "scope.driver", "waveform.*"),
    ),
    InstrumentPlugin(
        driver_id="rigol.dg4202",
        kind="source",
        display_name="RIGOL DG4202 Function/Arbitrary Waveform Generator",
        manufacturer="RIGOL Technologies",
        models=("DG4202", "DG4000"),
        capabilities=(
            "source.idn",
            "source.errors",
            "source.status",
            "source.set_frequency",
            "source.set_function",
            "source.set_amplitude_vpp",
            "source.set_square_duty_cycle",
            "source.output",
            "source.arbitrary_probe",
            "source.arbitrary_upload",
        ),
        summary="RIGOL DG4000-series signal source driver for frequency, waveform, output, and ARB flows.",
        idn_patterns=("RIGOL TECHNOLOGIES,DG4",),
        config_fields=("source.resource", "source.driver", "safety_limits.max_source_vpp"),
    ),
    InstrumentPlugin(
        driver_id="rigol.dp800",
        kind="power",
        display_name="RIGOL DP800 Power Supply",
        manufacturer="RIGOL Technologies",
        models=("DP800", "DP832", "DP832A"),
        capabilities=(
            "power.idn",
            "power.status",
            "power.measurement",
            "power.set_voltage_current_limit",
            "power.output",
            "power.protection",
        ),
        summary="RIGOL DP800-series programmable power supply driver with explicit safety limits.",
        idn_patterns=("RIGOL TECHNOLOGIES,DP8",),
        config_fields=(
            "power.resource",
            "power.driver",
            "safety_limits.max_power_voltage_v",
            "safety_limits.max_power_current_limit_a",
        ),
    ),
    InstrumentPlugin(
        driver_id="rigol.dm3000",
        kind="dmm",
        display_name="RIGOL DM3000/DM3058 Digital Multimeter",
        manufacturer="RIGOL Technologies",
        models=("DM3000", "DM3058"),
        capabilities=(
            "dmm.idn",
            "dmm.read",
            "dmm.function_status",
            "dmm.set_function",
        ),
        summary="RIGOL DM3000-family DMM driver for configured serial or VISA backends.",
        idn_patterns=("RIGOL TECHNOLOGIES,DM3", "RIGOL TECHNOLOGIES,DM3058"),
        config_fields=(
            "dmm.resource",
            "dmm.driver",
            "dmm.backend",
            "dmm.baudrate",
            "dmm.bytesize",
            "dmm.parity",
            "dmm.stopbits",
            "dmm.write_termination",
            "dmm.read_termination",
            "dmm.xonxoff",
            "dmm.rtscts",
            "dmm.dsrdtr",
        ),
    ),
)
